<?php
    class objetos{
        public $link;
        public $image;
        public $label;
    }
    $btn = array();

    $btn[0] = new objetos();
    $btn[0]->link = "pre-matricula";
    $btn[0]->image = "./assets/images/logotipo.png";
    $btn[0]->label = "Pré-Matrícula";
    $btn[1] = new objetos();
    $btn[1]->link = "pages\horario.php";
    $btn[1]->image = "./assets/images/logotipo.png";
    $btn[1]->label = "Horários";
    $btn[2] = new objetos();
    $btn[2]->link = "pages/turmas.php?action=getTurmas&ano=20211";
    $btn[2]->image = "./assets/images/logotipo.png";
    $btn[2]->label = "Turmas";
    $btn[3] = new objetos();
    $btn[3]->link = "Chat-2021";
    $btn[3]->image = "./assets/images/logotipo.png";
    $btn[3]->label = "Chat 2021";
    $btn[4] = new objetos();
    $btn[4]->link = "Boletos";
    $btn[4]->image = "./assets/images/logotipo.png";
    $btn[4]->label = "Boletos";
    $btn[5] = new objetos();
    $btn[5]->link = "IRPF";
    $btn[5]->image = "./assets/images/logotipo.png";
    $btn[5]->label = "IRPF";
    $btn[6] = new objetos();
    $btn[6]->link = "Boletim";
    $btn[6]->image = "./assets/images/logotipo.png";
    $btn[6]->label = "Boletim";
    $btn[7] = new objetos();
    $btn[7]->link = "Conteudo-Programatico";
    $btn[7]->image = "./assets/images/logotipo.png";
    $btn[7]->label = "Conteúdo Programático";
    $btn[8] = new objetos();
    $btn[8]->link = "Calendario";
    $btn[8]->image = "./assets/images/logotipo.png";
    $btn[8]->label = "Calendário";
    $btn[9] = new objetos();
    $btn[9]->link = "Colonia-de-Ferias";
    $btn[9]->image = "./assets/images/logotipo.png";
    $btn[9]->label = "Colônia de Férias";
    $btn[10] = new objetos();
    $btn[10]->link = "Material-Didático";
    $btn[10]->image = "./assets/images/logotipo.png";
    $btn[10]->label = "Material Didático";  
    $btn[11] = new objetos();
    $btn[11]->link = "Ocorrencias";
    $btn[11]->image = "./assets/images/logotipo.png";
    $btn[11]->label = "Ocorrências";
    $btn[12] = new objetos();
    $btn[12]->link = "Biblioteca";
    $btn[12]->image = "./assets/images/logotipo.png";
    $btn[12]->label = "Biblioteca";
    $btn[13] = new objetos();
    $btn[13]->link = "Acessos";
    $btn[13]->image = "./assets/images/logotipo.png";
    $btn[13]->label = "Acessos";
    $btn[14] = new objetos();
    $btn[14]->link = "Chat-Externo";
    $btn[14]->image = "./assets/images/logotipo.png";
    $btn[14]->label = "Chat Externo";
    $btn[15] = new objetos();
    $btn[15]->link = "Ensino-Medio-II";
    $btn[15]->image = "./assets/images/logotipo.png";
    $btn[15]->label = "Ensino Médio II";
    $btn[16] = new objetos();
    $btn[16]->link = "Senha";
    $btn[16]->image = "./assets/images/logotipo.png";
    $btn[16]->label = "Senha";
?>
